In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
zero_dim = tf.constant(4)
print(zero_dim)

one_dim = tf.constant([2, 0, -3])
print(one_dim)

two_dim = tf.constant([
    [56, 67, -3],
    [4, 88, -100]
])
print(two_dim)

three_dim = tf.constant([
    [[56, 67, -3],
    [4, 88, -100]],

    [[56, 67, -3],
    [4, 88, -100]],

    [[56, 67, -3],
    [4, 88, -100]],

    [[56, 67, -3],
    [4, 88, -100]]
])
print(three_dim)

four_dim = tf.constant([
    [
      [[56, 67, -3],
      [4, 88, -100]],

      [[56, 67, -3],
      [4, 88, -100]],

      [[56, 67, -3],
      [4, 88, -100]],

      [[56, 67, -3],
      [4, 88, -100]]
    ],

    [
      [[56, 67, -3],
      [4, 88, -100]],

      [[56, 67, -3],
      [4, 88, -100]],

      [[56, 67, -3],
      [4, 88, -100]],

      [[56, 67, -3],
      [4, 88, -100]]
    ],

], dtype='int16')
print(four_dim)

string_tensor = tf.constant(['Hello', 'World'])
print(string_tensor)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)
tf.Tensor(
[[  56   67   -3]
 [   4   88 -100]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[  56   67   -3]
  [   4   88 -100]]

 [[  56   67   -3]
  [   4   88 -100]]

 [[  56   67   -3]
  [   4   88 -100]]

 [[  56   67   -3]
  [   4   88 -100]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[[[  56   67   -3]
   [   4   88 -100]]

  [[  56   67   -3]
   [   4   88 -100]]

  [[  56   67   -3]
   [   4   88 -100]]

  [[  56   67   -3]
   [   4   88 -100]]]


 [[[  56   67   -3]
   [   4   88 -100]]

  [[  56   67   -3]
   [   4   88 -100]]

  [[  56   67   -3]
   [   4   88 -100]]

  [[  56   67   -3]
   [   4   88 -100]]]], shape=(2, 4, 2, 3), dtype=int16)
tf.Tensor([b'Hello' b'World'], shape=(2,), dtype=string)


In [ ]:
print(four_dim.shape)
print(four_dim.ndim)

(2, 4, 2, 3)
4


In [ ]:
# Converting numpy array to Tensor
np_arr = np.array([-11, 2, 3])
tf_arr = tf.convert_to_tensor(np_arr, dtype='int16')

print(np_arr)
print(tf_arr)

[-11   2   3]
tf.Tensor([-11   2   3], shape=(3,), dtype=int16)


In [ ]:
# Identity matrix
identity_mat = tf.eye(
    num_rows = 4,
    num_columns=None,
    batch_shape=(3,2),
    dtype=tf.dtypes.int16,
    name='Hello'
)

fill_tf = tf.fill(
    dims=(3,2), value=2, name=None, layout=None
)


fill_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2],
       [2, 2]], dtype=int32)>

In [ ]:
# Rabdom Tensor
normal_random_tf = tf.random.normal(
    shape=(3,4),
    mean=1.0,
    stddev=0.01,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

uniform_random_tf = tf.random.uniform(
    shape=(3,3),
    minval=5,
    maxval=10,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
uniform_random_tf

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[6.7539043, 9.654285 , 9.667868 ],
       [9.890403 , 6.7703066, 5.9088492],
       [5.7752075, 8.636847 , 8.501983 ]], dtype=float32)>

In [ ]:
# Indexing in tensor
tf_ind = tf.constant([32,2,100,88,12,444], dtype=tf.int16)
# print(tf_ind[2:5+1])

print(three_dim[1:3,...,:]) # '...' cannot be used as last index parameter. use ':'.
print(three_dim[...,:,2:3])

# Creating range of tensor
# print(tf.range(4, 10, 0.4))

tf.Tensor(
[[[  56   67   -3]
  [   4   88 -100]]

 [[  56   67   -3]
  [   4   88 -100]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[  -3]
  [-100]]

 [[  -3]
  [-100]]

 [[  -3]
  [-100]]

 [[  -3]
  [-100]]], shape=(4, 2, 1), dtype=int32)


In [ ]:
## Maths
# Absolute value
# tf.abs(tf.constant([-.5, 0, 32]))

# Absolute value of complex number
print(tf.abs(tf.constant(3 + 4j)))

tf.Tensor(5.0, shape=(), dtype=float64)


In [ ]:
t1 = tf.constant([
    [[1,2,3],
    [4,5,6]]
])
t2 = tf.constant([
    [[7,8,9],
    [10,11,12]]
])

print(f"t1 shape: {t1.shape}")
print(f"t2 shape: {t2.shape}")
print(f"concat shape: {tf.concat([t1, t2], axis=0).shape}")
print(f"stack shape: {tf.stack([t1, t2], axis=0).shape}")

t1 shape: (1, 2, 3)
t2 shape: (1, 2, 3)
concat shape: (2, 2, 3)
stack shape: (2, 1, 2, 3)


Ragged Tensor


In [ ]:
# Ragged Tensor
tensor_ragged = tf.ragged.constant([
    [3,2],
    [4],
    [100,23,2]
])

# Sparsed Tensor

sparse_tensor = tf.sparse.SparseTensor(
    indices=[[2,2], [4,4]],
    values=[55, 99],
    dense_shape=(6,6)
)
print(sparse_tensor)
tf.sparse.to_dense(sparse_tensor)


SparseTensor(indices=tf.Tensor(
[[2 2]
 [4 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([55 99], shape=(2,), dtype=int32), dense_shape=tf.Tensor([6 6], shape=(2,), dtype=int64))


<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0, 55,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 99,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>